<?php

declare(strict_types=1);

namespace Simtabi\Laranail\Toolkit\Tests\Unit\Console;

use Illuminate\Contracts\Console\Kernel;
use Simtabi\Laranail\Toolkit\Tests\TestCase;

class NamespacedCommandTest extends TestCase
{
    protected function tearDown(): void
    {
        // Remove any artifacts generated by the invokable-command test.
        @unlink(app_path('Models/Widget.php'));
        @unlink(app_path('Http/Controllers/WidgetController.php'));

        foreach (glob(database_path('migrations/*_create_widgets_table.php')) ?: [] as $migration) {
            @unlink($migration);
        }

        parent::tearDown();
    }

    public function test_command_registers_under_the_org_namespaced_name(): void
    {
        $commands = $this->app[Kernel::class]->all();

        $this->assertArrayHasKey('laranail::toolkit.make-crud', $commands);
    }

    public function test_make_crud_alias_resolves_to_the_namespaced_command(): void
    {
        $commands = $this->app[Kernel::class]->all();

        $this->assertArrayHasKey('make:crud', $commands);
        $this->assertSame(
            $commands['laranail::toolkit.make-crud'],
            $commands['make:crud'],
        );
    }

    public function test_namespaced_command_is_invokable(): void
    {
        $this->artisan('laranail::toolkit.make-crud', ['name' => 'Widget'])
            ->assertExitCode(0);
    }
}
