<?php

declare(strict_types=1);

/**
 * laranail/toolkit — IDE helper stub for runtime-registered macros.
 *
 * GENERATED by `php artisan laranail::toolkit.ide-helper-macros`
 * (alias `ide-helper:macros`). Do NOT edit by hand — regenerate instead.
 *
 * The toolkit registers many macros on Illuminate's macroable targets
 * (Str, Stringable, Collection, Arr, the query/Eloquent builders, Blueprint,
 * Request, Carbon) plus a Factory mixin. Those are added at boot via
 * `Macroable::macro()` / `Factory::mixin()`, so a static analyser / IDE cannot
 * see them and will not autocomplete or type them.
 *
 * This file re-opens each Illuminate namespace and re-declares the real class
 * with `@method` / `@method static` PHPDoc tags for every registered macro.
 * PhpStorm and VS Code (Intelephense) MERGE these tags onto the real class.
 *
 * IMPORTANT — this file is NEVER loaded at runtime:
 *   - it is NOT listed in composer.json `autoload.files`;
 *   - it lives OUTSIDE the `src/` PSR-4 root, so it is never autoloaded;
 *   - IDEs index it statically (they parse, they do not execute it).
 *
 * Do NOT `require` this file. Do NOT add it to composer autoload.
 *
 * @noinspection ALL
 *
 * phpcs:ignoreFile
 */

namespace Illuminate\Support {
    /**
     * @method static string                         camelToTitle(string $string)
     * @method static int                            countWords(string $string)
     * @method static \Illuminate\Support\HtmlString highlightWords(string $string, mixed $words)
     * @method static string                         interpolate(string $string, array $replacements)
     * @method static bool                           isEmail(string $string)
     * @method static string                         kebabToTitle(string $string)
     * @method static int                            linesCount(string $string)
     * @method static bool                           matches(string $string, string $pattern)
     * @method static string                         normalizeWhitespace(string $string)
     * @method static int                            readingMinutes(string $string, int $wordsPerMinute = 200)
     * @method static string                         removeAccents(string $string)
     * @method static string                         replaceMany(string $string, array $replacements)
     * @method static string                         reverseString(string $string)
     * @method static string                         snakeToTitle(string $string)
     * @method static string                         stripTags(string $string, mixed $allowedTags = null)
     * @method static string                         stripWhitespace(string $string)
     * @method static bool                           toBool(string $string)
     * @method static string                         truncateMiddle(string $string, int $length = 50, string $middle = '...')
     * @method static string                         wrapWith(string $string, string $wrapper = '"')
     */
    class Str {}

    /**
     * @method \Illuminate\Support\Stringable camelToTitle()
     * @method int                            countWords()
     * @method \Illuminate\Support\HtmlString highlightWords(mixed $words)
     * @method \Illuminate\Support\Stringable interpolate(array $replacements)
     * @method bool                           isEmail()
     * @method \Illuminate\Support\Stringable kebabToTitle()
     * @method int                            linesCount()
     * @method bool                           matches(string $pattern)
     * @method \Illuminate\Support\Stringable normalizeWhitespace()
     * @method int                            readingMinutes(int $wordsPerMinute = 200)
     * @method \Illuminate\Support\Stringable removeAccents()
     * @method \Illuminate\Support\Stringable reverseString()
     * @method \Illuminate\Support\Stringable snakeToTitle()
     * @method \Illuminate\Support\Stringable stripWhitespace()
     * @method bool                           toBool()
     * @method \Illuminate\Support\Stringable truncateMiddle(int $length = 50, string $middle = '...')
     * @method \Illuminate\Support\Stringable wrapWith(string $wrapper = '"')
     */
    class Stringable {}

    /**
     * @method mixed                          averageBy(callable $callback)
     * @method mixed                          before(mixed $current, bool $strict = false)
     * @method \Illuminate\Support\Collection chunkBy(callable $callback, bool $preserveKeys = false)
     * @method \Illuminate\Support\Collection collectBy(mixed $key, mixed $default = null)
     * @method \Illuminate\Support\Collection eachCons(int $chunkSize, bool $preserveKeys = false)
     * @method \Illuminate\Support\Collection extract(mixed $keys)
     * @method \Illuminate\Support\Collection filterMap(callable $callback)
     * @method \Illuminate\Support\Collection filterRecursive(?callable $callback = null)
     * @method mixed                          firstOrFail(?callable $callback = null, mixed $default = null)
     * @method mixed                          firstOrPush(callable $callback, mixed $value, ?\Illuminate\Support\Collection $instance = null)
     * @method array                          forSelectBox(string $key, string $value, bool $addEmpty = true)
     * @method \Illuminate\Support\Collection fromPairs()
     * @method \Illuminate\Support\Collection groupByModel(mixed $callback, mixed $modelKey = 0, mixed $itemsKey = 1)
     * @method \Illuminate\Support\Collection ifAny(callable $callback)
     * @method \Illuminate\Support\Collection ifEmpty(callable $callback)
     * @method \Illuminate\Support\Collection insertAfter(mixed $key, mixed $value)
     * @method \Illuminate\Support\Collection insertAfterKey(mixed $afterKey, mixed $item, mixed $key = null)
     * @method \Illuminate\Support\Collection insertAt(int $index, mixed $item, mixed $key = null)
     * @method \Illuminate\Support\Collection insertBefore(mixed $key, mixed $value)
     * @method \Illuminate\Support\Collection insertBeforeKey(mixed $beforeKey, mixed $item, mixed $key = null)
     * @method \Illuminate\Support\Collection mapKeyValuePairs()
     * @method \Illuminate\Support\Collection mapToKey(callable $callback)
     * @method bool                           none(mixed $key, mixed $value = null)
     * @method \Illuminate\Support\Collection pluckMany(array $keys)
     * @method array                          pluckToArray(mixed $value, ?string $key = null)
     * @method \Illuminate\Support\Collection prioritize(callable $callback)
     * @method \Illuminate\Support\Collection recursive()
     * @method \Illuminate\Support\Collection replaceInKeys(mixed $search, mixed $replace)
     * @method \Illuminate\Support\Collection rotate(int $offset)
     * @method \Illuminate\Support\Collection rotateLeft(int $count = 1)
     * @method \Illuminate\Support\Collection rotateRight(int $count = 1)
     * @method \Illuminate\Support\Collection sectionBy(mixed $key, bool $preserveKeys = false, mixed $sectionKey = 0, mixed $itemsKey = 1)
     * @method \Illuminate\Support\Collection sliceBefore(callable $callback, bool $preserveKeys = false)
     * @method \Illuminate\Support\Collection sortSearchResults(string $searchTerms, string $column)
     * @method mixed                          sumRecursive(mixed $key = null)
     * @method \Illuminate\Support\Collection tail(bool $preserveKeys = false)
     * @method array                          toCsv(string $delimiter = ',', string $enclosure = '"', string $escape = '\\')
     * @method \Illuminate\Support\Collection toPairs()
     * @method \Illuminate\Support\Collection toTree(string $parentKey = 'parent_id', string $childrenKey = 'children')
     * @method \Illuminate\Support\Collection transpose()
     * @method \Illuminate\Support\Collection withSize(int $size)
     */
    class Collection {}

    /**
     * @method static mixed average(array $array, ?string $key = null)
     * @method static array filterEmpty(array $array)
     * @method static array filterNulls(array $array)
     * @method static array groupByKey(array $array, string $key)
     * @method static array insertAfter(array $array, mixed $key, array $insert)
     * @method static array insertBefore(array $array, mixed $key, array $insert)
     * @method static array mapKeys(array $array, callable $callback)
     * @method static mixed median(array $array, ?string $key = null)
     * @method static array removeValue(array $array, mixed $value)
     * @method static array removeValues(array $array, array $values)
     * @method static array renameKey(array $array, mixed $oldKey, mixed $newKey)
     * @method static array renameKeys(array $array, array $changes)
     * @method static array sortByKeys(array $array, array $keys)
     * @method static array uniqueBy(array $array, string $key)
     */
    class Arr {}

    /**
     * @method \Illuminate\Support\Carbon  addBusinessDays(int $days)
     * @method ?\Illuminate\Support\Carbon fromDateTimeLocalString(string $string)
     * @method int                         getQuarter()
     * @method bool                        isAllSaintsDay()
     * @method bool                        isAmericanThanksgiving()
     * @method bool                        isAscensionDay()
     * @method bool                        isAscensionOfJesus()
     * @method bool                        isAssumptionDay()
     * @method bool                        isAssumptionOfMaryFeast()
     * @method bool                        isBoxingDay()
     * @method bool                        isBrazilianDayOfTheDead()
     * @method bool                        isBrazilianIndependenceDay()
     * @method bool                        isBrazilianLaborDay()
     * @method bool                        isBrazilianRepublicProclamationDay()
     * @method bool                        isCanadaDay()
     * @method bool                        isCanadianThanksgiving()
     * @method bool                        isChristmasDay()
     * @method bool                        isChristmasEve()
     * @method bool                        isCivicHoliday()
     * @method bool                        isColumbusDay()
     * @method bool                        isCorpusChristi()
     * @method bool                        isDutchLiberationDay()
     * @method bool                        isDutchNationalDay()
     * @method bool                        isDutchRemembranceDay()
     * @method bool                        isEasterMonday()
     * @method bool                        isEasterSunday()
     * @method bool                        isEpiphany()
     * @method bool                        isFamilyDay()
     * @method bool                        isFirstDayOfMonth()
     * @method bool                        isFirstWarArmisticeDay()
     * @method bool                        isFrenchNationalDay()
     * @method bool                        isGandhiJayanti()
     * @method bool                        isGermanLabourDay()
     * @method bool                        isGermanUnityDay()
     * @method bool                        isGoodFriday()
     * @method bool                        isHeiligAbend()
     * @method bool                        isHeiligerAbend()
     * @method bool                        isImmaculateConceptionFeast()
     * @method bool                        isIndependenceDay()
     * @method bool                        isIndianIndependenceDay()
     * @method bool                        isIndianRepublicDay()
     * @method bool                        isIndonesiaCustomerDay()
     * @method bool                        isIndonesianEducationDay()
     * @method bool                        isIndonesianHeroesDay()
     * @method bool                        isIndonesianIndependenceDay()
     * @method bool                        isIndonesianLaborDay()
     * @method bool                        isIndonesianMothersDay()
     * @method bool                        isKartiniDay()
     * @method bool                        isKenyanHudumaDay()
     * @method bool                        isKenyanIndependenceDay()
     * @method bool                        isKenyanJamhuriDay()
     * @method bool                        isKenyanLabourDay()
     * @method bool                        isKenyanMadarakaDay()
     * @method bool                        isKenyanMashujaaDay()
     * @method bool                        isKenyanUtamaduniDay()
     * @method bool                        isKupalaNight()
     * @method bool                        isLaborDay()
     * @method bool                        isLabourDay()
     * @method bool                        isLastDayOfMonth()
     * @method bool                        isLiberationDay()
     * @method bool                        isMemorialDay()
     * @method bool                        isMlkJrDay()
     * @method bool                        isNewYearsDay()
     * @method bool                        isNewYearsEve()
     * @method bool                        isPancasilaDay()
     * @method bool                        isPentecost()
     * @method bool                        isPentecostDay()
     * @method bool                        isPentecostMonday()
     * @method bool                        isPentecostSunday()
     * @method bool                        isPresidentsDay()
     * @method bool                        isRemembranceDay()
     * @method bool                        isRepublicDay()
     * @method bool                        isSaintNicholasEve()
     * @method bool                        isSaintStephenDay()
     * @method bool                        isSaintSylvesterDay()
     * @method bool                        isSecondWarArmisticeDay()
     * @method bool                        isSwedishMidsummerDay()
     * @method bool                        isSwedishNationalDay()
     * @method bool                        isTheDayOfOurLadyAparecida()
     * @method bool                        isTiradentesDay()
     * @method bool                        isUkraineDefenderDay()
     * @method bool                        isUkrainianConstitutionDay()
     * @method bool                        isUkrainianIndependenceDay()
     * @method bool                        isUkrainianLabourDay()
     * @method bool                        isVeteransDay()
     * @method bool                        isVictoriaDay()
     * @method bool                        isVictoryDayOverNazism()
     * @method bool                        isWhitMonday()
     * @method bool                        isWhitSunday()
     * @method bool                        isWhitsun()
     * @method bool                        isWorkersDay()
     * @method bool                        isZambianAfricaDay()
     * @method bool                        isZambianAfricanUnityDay()
     * @method bool                        isZambianFarmersDay()
     * @method bool                        isZambianHeroesDay()
     * @method bool                        isZambianIndependenceDay()
     * @method bool                        isZambianLabourDay()
     * @method bool                        isZambianNationalPrayerDay()
     * @method bool                        isZambianUnityDay()
     * @method bool                        isZambianWomensDay()
     * @method bool                        isZambianYouthDay()
     * @method \Illuminate\Support\Carbon  subBusinessDays(int $days)
     * @method string                      toHumanReadableString()
     */
    class Carbon {}
}

namespace Illuminate\Database\Query {
    /**
     * @method \Illuminate\Database\Query\Builder log(?string $channel = null)
     * @method \Illuminate\Database\Query\Builder orderByNullsFirst(string $column, string $direction = 'asc')
     * @method \Illuminate\Database\Query\Builder orderByNullsLast(string $column, string $direction = 'asc')
     * @method \Illuminate\Database\Query\Builder whenFilled(mixed $value, callable $callback)
     * @method \Illuminate\Database\Query\Builder whereBetweenDates(string $column, mixed $startDate, mixed $endDate)
     */
    class Builder {}
}

namespace Illuminate\Database\Eloquent {
    /**
     * @method mixed                                 doesntExistOr(callable $callback)
     * @method mixed                                 existsOr(callable $callback)
     * @method \Illuminate\Database\Eloquent\Builder whenFilled(mixed $value, callable $callback)
     * @method \Illuminate\Database\Eloquent\Builder whereBetweenDates(string $column, mixed $startDate, mixed $endDate)
     */
    class Builder {}
}

namespace Illuminate\Database\Schema {
    /**
     * @method void                                  addActivationFields()
     * @method void                                  addCommonFields()
     * @method void                                  addExpiryFields()
     * @method void                                  addImageFields(string $prefix = '')
     * @method void                                  addLocationFields()
     * @method void                                  addMetaFields()
     * @method void                                  addNullableMorphs(string $name, ?string $indexName = null)
     * @method void                                  addPriceFields()
     * @method void                                  addPublishingFields()
     * @method void                                  addSeoFields()
     * @method \Illuminate\Database\Schema\Blueprint addSlugField(bool $nullable = false)
     * @method void                                  addSortingField(int $default = 0)
     * @method void                                  addStatusField(string $default = 'active')
     * @method void                                  addUserFields()
     * @method void                                  addUuidPrimaryKey(string $column = 'id')
     * @method void                                  dropColumnIfExists(mixed $columns)
     * @method void                                  dropForeignIfExists(string $index)
     */
    class Blueprint {}
}

namespace Illuminate\Http {
    /**
     * @method bool                     expectsJsonOrAjax()
     * @method ?string                  getReferer(?string $default = null)
     * @method bool                     hasAny(array $keys)
     * @method bool                     hasFiles(array $keys)
     * @method bool                     hasValidFile(string $key)
     * @method \Illuminate\Http\Request hasValidRelativeSignature()
     * @method \Illuminate\Http\Request hasValidRelativeSignatureWhileIgnoring($ignoreQuery = [])
     * @method \Illuminate\Http\Request hasValidSignature($absolute = true)
     * @method \Illuminate\Http\Request hasValidSignatureWhileIgnoring($ignoreQuery = [], $absolute = true)
     * @method bool                     isBot()
     * @method bool                     isFromDomain(string $domain)
     * @method bool                     isFromMobile()
     * @method bool                     isJsonRequest()
     * @method \Illuminate\Http\Request mergeIfMissing(array $values)
     * @method array                    onlyFilled(array $keys)
     * @method \Illuminate\Http\Request validate(array $rules, ...$params)
     * @method \Illuminate\Http\Request validateWithBag(string $errorBag, array $rules, ...$params)
     */
    class Request {}
}

namespace Illuminate\Routing {
    /**
     * @method \Illuminate\Http\JsonResponse error(string $message = 'Bad Request', int $status = 400, array $errors = [], mixed $debug = null)
     * @method \Illuminate\Http\JsonResponse message(string $message, int $status = 200)
     * @method \Illuminate\Http\Response     pdf(string $pdf, string $fileName = 'document.pdf', bool $download = false)
     * @method \Illuminate\Http\JsonResponse success(mixed $data = null, string $message = 'Request successful.', int $status = 200, array $meta = [])
     */
    class ResponseFactory {}
}

namespace Illuminate\Database\Eloquent\Factories {
    /**
     * @method \Illuminate\Database\Eloquent\Factories\Factory withoutEvents() Flush the model's event listeners for the factory chain.
     */
    class Factory {}
}
